using FluentAssertions;
using WeatherSynth;
using Xunit;

namespace WeatherSynthApiTests;

/// <summary>
/// The bundled model against the records it was fitted from.
///
/// <para><b>This is what stops the coefficients going stale.</b> <c>BochumEssenCoefficients.g.cs</c>
/// is generated by the <c>exportmodel</c> sample command and then sits in source, where nothing
/// recomputes it. The first time anyone touches a fitter - a different Weibull estimator, a changed
/// support, a corrected filter - the checked-in numbers become a fossil of the old fit, and every
/// other test in the repository keeps passing, because they all fit from the CSVs. Only this
/// comparison notices. If it fails, re-run <c>exportmodel</c>.</para>
///
/// <para><b>Identical, not close.</b> Both sides drive the same chain from the same seed, so if the
/// coefficients round-tripped exactly the two day sequences agree bit for bit. A tolerance here
/// would pass a model that had drifted in the last few digits, which is exactly the failure worth
/// catching early.</para>
///
/// <para>Its limit, stated honestly: both sides run the same ceiling code, so this catches a stale
/// <i>resource</i>, not a changed <i>ceiling</i>. A change to the Linke turbidity table or the
/// integration step moves generated irradiance without moving any coefficient - that is a
/// modelling decision, not a staleness bug, and belongs to a different test.</para>
///
/// <para>Data-aware, like <c>GameUseCaseTests</c>: absent the station files the comparisons pass
/// silently. <see cref="Builds_and_generates_with_no_data_files_anywhere"/> does not depend on them
/// and is the one that proves the package case.</para>
/// </summary>
public class DefaultModelTests
{
    private const int Year = 2027;
    private const int Seed = 4242;

    [Fact]
    public void Solar_matches_a_fit_from_the_record()
    {
        if (GameUseCaseTests.SolarCsvPath is null)
            return;

        var fitted = SyntheticSolarProvider.FromDwdRecord(
            GameUseCaseTests.SolarCsvPath,
            DwdSolarStations.Bochum
        );

        var fromRecord = fitted.GenerateYear(Year, Seed);
        var fromCoefficients = SyntheticWeather.DefaultSolar.GenerateYear(Year, Seed);

        fromCoefficients.Days.Should().Equal(fromRecord.Days);
        fromCoefficients.GhiKWhPerM2.Should().Be(fromRecord.GhiKWhPerM2);
    }

    [Fact]
    public void Wind_matches_a_fit_from_the_record()
    {
        if (GameUseCaseTests.WindCsvPath is null)
            return;

        var fitted = SyntheticWindProvider.FromDwdRecord(
            GameUseCaseTests.WindCsvPath,
            DwdWindStations.EssenBredeney
        );

        var fromRecord = fitted.GenerateYear(Year, Seed);
        var fromCoefficients = SyntheticWeather.DefaultWind.GenerateYear(Year, Seed);

        fromCoefficients.Days.Should().Equal(fromRecord.Days);
        fromCoefficients.MeanSpeed.Should().Be(fromRecord.MeanSpeed);

        // The intra-day shape is carried separately from the speed model and only the yield
        // consumes it, so a speed comparison alone would not notice it drifting.
        var yieldFromRecord = fitted.EstimateYield(
            Year,
            Seed,
            ReferenceTurbines.Generic2Mw,
            ReferenceTurbines.HundredMetreHub
        );

        var yieldFromCoefficients = SyntheticWeather.DefaultWind.EstimateYield(
            Year,
            Seed,
            ReferenceTurbines.Generic2Mw,
            ReferenceTurbines.HundredMetreHub
        );

        yieldFromCoefficients.CapacityFactor.Should().Be(yieldFromRecord.CapacityFactor);
        yieldFromCoefficients.Days.Should().Equal(yieldFromRecord.Days);
    }

    [Fact]
    public void Coupled_matches_a_fit_from_both_records()
    {
        if (GameUseCaseTests.SolarCsvPath is null || GameUseCaseTests.WindCsvPath is null)
            return;

        var fitted = CoupledWeatherProvider.FromDwdRecords(
            GameUseCaseTests.SolarCsvPath,
            DwdSolarStations.Bochum,
            GameUseCaseTests.WindCsvPath,
            DwdWindStations.EssenBredeney
        );

        var fromRecord = fitted.GenerateYear(Year, Seed);
        var fromCoefficients = SyntheticWeather.Default.GenerateYear(Year, Seed);

        // The whole pairing, which is the half the coupling coefficients are responsible for.
        fromCoefficients.Days.Should().Equal(fromRecord.Days);

        // And every hour, which is what the diurnal and persistence coefficients are for.
        fromCoefficients.Hours.Should().Equal(fromRecord.Hours);
    }

    /// <summary>
    /// The package condition, which the skip-if-absent comparisons above cannot assert: a consumer
    /// has no <c>data/</c> directory anywhere above them, and everything must still work.
    /// </summary>
    [Fact]
    public void Builds_and_generates_with_no_data_files_anywhere()
    {
        var year = SyntheticWeather.Default.GenerateYear(Year, Seed);

        year.Days.Should().HaveCount(365);
        year.Solar.GhiKWhPerM2.Should().BeInRange(700.0, 1400.0);
        year.Wind.MeanSpeed.Should().BeInRange(2.0, 8.0);

        SyntheticWeather.IsCreated.Should().BeTrue();
    }

    /// <summary>
    /// One model, not three. A caller reaching for <see cref="SyntheticWeather.DefaultSolar"/> and
    /// <see cref="SyntheticWeather.Default"/> in the same process must get the same fitted object,
    /// or the two would agree in distribution and disagree on any given seed.
    /// </summary>
    [Fact]
    public void The_coupled_default_is_composed_from_the_two_single_defaults()
    {
        SyntheticWeather.Default.Solar.Should().BeSameAs(SyntheticWeather.DefaultSolar);
        SyntheticWeather.Default.Wind.Should().BeSameAs(SyntheticWeather.DefaultWind);

        // And repeated access does not rebuild.
        SyntheticWeather.Default.Should().BeSameAs(SyntheticWeather.Default);
    }

    /// <summary>
    /// The bundled model is still the Bochum/Essen one. A coefficient file swapped for another
    /// station would pass every comparison above if the CSVs were swapped too; these are the
    /// published figures from knowledge.md, and they are what pins it.
    /// </summary>
    [Fact]
    public void Carries_the_documented_fit()
    {
        var year = SyntheticWeather.Default.GenerateYear(Year, Seed);

        // Bochum: ~1,000 kWh/m² a year at 51.4°N, and a mean clear-sky index near 0.59.
        year.Solar.MeanClearSkyIndex.Should().BeApproximately(0.59, 0.05);

        // Essen-Bredeney at its 15 m anemometer: a little over 3 m/s.
        year.Wind.MeanSpeed.Should().BeApproximately(3.2, 0.5);
    }
}
