using System.Globalization;
using System.Text;
using WeatherSynth.Climate;
using WeatherSynth.Data;
using WeatherSynth.Wind;

namespace WeatherSynth.Sample;

/// <summary>
/// Writes the fitted coefficients out as C# source, so the library can carry the model without
/// carrying the record.
///
/// <para><b>Why this exists.</b> The two station files total 30 MB. Everything learned from them is
/// 86 doubles - twelve Beta pairs, twelve Weibull triples, two persistence coefficients, twelve
/// coupling coefficients and a handful of scalars. Fitting is deterministic given frozen data, so a
/// published package has no reason to ship the CSVs or to redo the fit on every launch. This
/// command is the bridge: the records stay here as the source of truth, and only their conclusion
/// ships.</para>
///
/// <para><b>It fits through <see cref="CoupledWeatherProvider.FromStationDays"/>, on purpose.</b>
/// That is the same call <c>couple</c> makes, so the exported numbers cannot drift from the ones
/// every report prints - there is no second fitting path to keep in step.</para>
///
/// <para><b>Round-trip formatting is load-bearing.</b> Every value is written with "R", which on
/// this runtime is the shortest string that parses back to the identical bits.
/// <c>DefaultModelTests</c> asserts the rebuilt model reproduces a freshly fitted year
/// <i>exactly</i>, and anything less than round-trip formatting fails it - as it should, because a
/// coefficient that is nearly right is a model that is quietly wrong.</para>
/// </summary>
internal static class ModelExport
{
    /// <summary>Where the generated file goes, relative to the repository root.</summary>
    private const string OutputDirectory = "src/WeatherSynth.Data/Resources";

    private const string OutputFileName = "BochumEssenCoefficients.g.cs";

    public static int Run(
        IReadOnlyList<DwdSolarDay> solarDays,
        DwdSolarStation solarStation,
        IReadOnlyList<DwdWindDay> windDays,
        DwdWindStation windStation,
        string[] args
    )
    {
        string? outputPath = args.Length > 1 ? args[1] : LocateDefaultOutput();
        if (outputPath is null)
        {
            Console.Error.WriteLine(
                $"Could not find {OutputDirectory} in any parent directory. "
                    + "Pass an output path: exportmodel <path>"
            );
            return 1;
        }

        Console.WriteLine("Fitting both records (the same path 'couple' takes) ...");

        var coupled = CoupledWeatherProvider.FromStationDays(
            solarDays,
            solarStation,
            windDays,
            windStation
        );

        string source = Render(
            coupled.Solar.Model,
            coupled.Wind.Model,
            coupled.Wind.IntradayShape,
            coupled.Coupling,
            solarDays,
            solarStation,
            windDays,
            windStation
        );

        Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);

        // Newlines normalised, so the file is identical whatever platform generated it and a
        // re-run diffs cleanly.
        File.WriteAllText(outputPath, source.Replace("\r\n", "\n"));

        Console.WriteLine($"Wrote {outputPath}");
        Console.WriteLine($"{source.Split('\n').Length:N0} lines, {source.Length:N0} bytes.");
        Console.WriteLine();
        Console.WriteLine(
            "Re-run the tests: DefaultModelTests asserts the rebuilt model reproduces a freshly "
                + "fitted year exactly."
        );

        return 0;
    }

    private static string Render(
        ClearSkyIndexModel solar,
        WindSpeedModel wind,
        IntradayShapeModel intraday,
        MonthlyCoupling coupling,
        IReadOnlyList<DwdSolarDay> solarDays,
        DwdSolarStation solarStation,
        IReadOnlyList<DwdWindDay> windDays,
        DwdWindStation windStation
    )
    {
        var monthlySolar = Enumerable.Range(1, 12).Select(solar.ForMonth).ToList();
        var monthlyWind = Enumerable.Range(1, 12).Select(wind.ForMonth).ToList();
        var couplingCounts = Enumerable.Range(1, 12).Select(coupling.SampleCount).ToList();

        var text = new StringBuilder();

        text.Append("// <auto-generated>\n")
            .Append(
                "//     Generated by the WeatherSynth.Sample 'exportmodel' command. Do not edit by\n"
            )
            .Append(
                "//     hand: the numbers below are a fit, and a hand-corrected fit is not a fit.\n"
            )
            .Append("//\n")
            .Append("//     To regenerate:\n")
            .Append(
                "//         dotnet run --project samples/WeatherSynth.Sample -c Release -- exportmodel\n"
            )
            .Append("//\n")
            .Append(
                $"//     Solar: {solarStation.Name} {solarStation.Id}, {Span(solarDays.Select(d => d.Date))}\n"
            )
            .Append(
                $"//     Wind:  {windStation.Name} {windStation.Id}, {Span(windDays.Select(d => d.Date))}\n"
            )
            .Append("//\n")
            .Append(
                "//     What is NOT in here, deliberately: the clear-sky ceiling, which is recomputed\n"
            )
            .Append(
                "//     at runtime from the site's geometry and the fitted Linke turbidity table, and\n"
            )
            .Append("//     both sites, which are already public constants (DwdSolarStations.Bochum,\n")
            .Append(
                "//     DwdWindStations.EssenBredeney). Only the stochastic half is frozen here.\n"
            )
            .Append("// </auto-generated>\n")
            .Append('\n')
            .Append("namespace WeatherSynth.Data;\n")
            .Append('\n')
            .Append("/// <summary>\n")
            .Append(
                "/// The bundled model, as coefficients. Rebuilt by <c>SyntheticWeather</c> through each\n"
            )
            .Append("/// model's <c>FromCoefficients</c>, which skips fitting entirely.\n")
            .Append("///\n")
            .Append(
                "/// <para>The twelve monthly entries are already <i>effective</i>: each model's Fit\n"
            )
            .Append(
                "/// substitutes the pooled fit for months too thin to stand alone, and does so once, at\n"
            )
            .Append("/// fit time. There is no fallback left to re-apply on load.</para>\n")
            .Append("/// </summary>\n")
            .Append("internal static class BochumEssenCoefficients\n")
            .Append("{\n");

        Comment(
            text,
            $"Clear-sky index: twelve Beta fits on [0, {Literal(solar.Support)}].",
            $"Days per month: {Counts(monthlySolar.Select(b => b.SampleCount))}"
        );
        Scalar(text, "SolarSupport", solar.Support);
        Scalar(text, "SolarPersistence", solar.Persistence);
        Scalar(text, "SolarPooledAlpha", solar.Pooled.Alpha);
        Scalar(text, "SolarPooledBeta", solar.Pooled.Beta);
        Doubles(text, "SolarAlpha", monthlySolar.Select(b => b.Alpha));
        Doubles(text, "SolarBeta", monthlySolar.Select(b => b.Beta));

        Comment(
            text,
            $"Wind speed: twelve three-parameter Weibull fits at {Literal(wind.ReferenceHeightMeters)} m.",
            $"Days per month: {Counts(monthlyWind.Select(w => w.SampleCount))}"
        );
        Scalar(text, "WindPersistence", wind.Persistence);
        Scalar(text, "WindReferenceHeightMeters", wind.ReferenceHeightMeters);
        Scalar(text, "WindMeanEnergyPatternFactor", wind.MeanEnergyPatternFactor);
        Scalar(text, "WindPooledShape", wind.Pooled.Shape);
        Scalar(text, "WindPooledScale", wind.Pooled.Scale);
        Scalar(text, "WindPooledLocation", wind.Pooled.Location);
        Doubles(text, "WindShape", monthlyWind.Select(w => w.Shape));
        Doubles(text, "WindScale", monthlyWind.Select(w => w.Scale));
        Doubles(text, "WindLocation", monthlyWind.Select(w => w.Location));

        Comment(
            text,
            "Intra-day shape: least squares of log(EPF) on log(mean speed). Only the turbine",
            "yield consumes it; speed generation is untouched by it."
        );
        Scalar(text, "IntradayIntercept", intraday.Intercept);
        Scalar(text, "IntradaySlope", intraday.Slope);
        Scalar(text, "IntradayPooledEnergyPatternFactor", intraday.PooledEnergyPatternFactor);
        Integer(text, "IntradaySampleCount", intraday.SampleCount);

        Comment(
            text,
            "Solar-wind coupling, solar first. Months below the minimum carry the pooled",
            "coefficient; the counts are kept so IsPooled can still say which those were.",
            $"Pairs per month: {Counts(couplingCounts)}"
        );
        Scalar(text, "CouplingPooled", coupling.Pooled);
        Doubles(text, "CouplingByMonth", Enumerable.Range(1, 12).Select(coupling.ForMonth));
        Integers(text, "CouplingCounts", couplingCounts);

        text.Append("}\n");

        return text.ToString();
    }

    private static void Comment(StringBuilder text, params string[] lines)
    {
        // A blank line between sections, but not one straight after the opening brace.
        if (text.Length >= 2 && text[^2] != '{')
            text.Append('\n');

        foreach (string line in lines)
            text.Append("    // ").Append(line).Append('\n');
    }

    private static void Scalar(StringBuilder text, string name, double value) =>
        text.Append("    internal const double ")
            .Append(name)
            .Append(" = ")
            .Append(Literal(value))
            .Append(";\n");

    private static void Integer(StringBuilder text, string name, int value) =>
        text.Append("    internal const int ")
            .Append(name)
            .Append(" = ")
            .Append(value.ToString(CultureInfo.InvariantCulture))
            .Append(";\n");

    private static void Doubles(StringBuilder text, string name, IEnumerable<double> values) =>
        Block(text, "double", name, values.Select(Literal));

    private static void Integers(StringBuilder text, string name, IEnumerable<int> values) =>
        Block(text, "int", name, values.Select(v => v.ToString(CultureInfo.InvariantCulture)));

    /// <summary>One array, one entry per line with its month named - twelve bare numbers on one
    /// line would be unreadable in a diff, and a diff is the only review this file ever gets.</summary>
    private static void Block(
        StringBuilder text,
        string type,
        string name,
        IEnumerable<string> literals
    )
    {
        text.Append("\n    internal static readonly ")
            .Append(type)
            .Append("[] ")
            .Append(name)
            .Append(" =\n    {\n");

        int month = 0;
        foreach (string literal in literals)
            text.Append("        ")
                .Append(literal)
                .Append(", // ")
                .Append(MonthNames[month++])
                .Append('\n');

        text.Append("    };\n");
    }

    private static readonly string[] MonthNames =
    {
        "Jan",
        "Feb",
        "Mar",
        "Apr",
        "May",
        "Jun",
        "Jul",
        "Aug",
        "Sep",
        "Oct",
        "Nov",
        "Dec",
    };

    private static string Span(IEnumerable<DateOnly> dates)
    {
        var list = dates.ToList();
        return $"{list.Count:N0} days, {list[0]:yyyy-MM-dd} to {list[^1]:yyyy-MM-dd}";
    }

    private static string Counts(IEnumerable<int> counts) =>
        string.Join(", ", counts.Select(c => c.ToString(CultureInfo.InvariantCulture)));

    /// <summary>
    /// One double as a C# literal, round-trip exact.
    ///
    /// <para>Non-finite values are refused rather than emitted: "NaN" is not a literal, and a
    /// coefficient that came out NaN is a broken fit that must not be frozen into source.</para>
    /// </summary>
    private static string Literal(double value)
    {
        if (!double.IsFinite(value))
            throw new InvalidOperationException(
                $"Refusing to emit a non-finite coefficient ({value}). The fit is broken; "
                    + "exporting it would freeze the breakage into source."
            );

        return value.ToString("R", CultureInfo.InvariantCulture);
    }

    /// <summary>Walks up from the running assembly for the repository's generated-source path.</summary>
    private static string? LocateDefaultOutput()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);

        while (directory is not null)
        {
            // Anchored on the project directory rather than on Resources/, which may not exist yet.
            string project = Path.Combine(
                directory.FullName,
                "src",
                "WeatherSynth.Data",
                "WeatherSynth.Data.csproj"
            );

            if (File.Exists(project))
                return Path.Combine(
                    directory.FullName,
                    OutputDirectory.Replace('/', Path.DirectorySeparatorChar),
                    OutputFileName
                );

            directory = directory.Parent;
        }

        return null;
    }
}
