<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <RootNamespace>WeatherModel.Sample</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../../src/WeatherModel.Core/WeatherModel.Core.csproj" />
        <ProjectReference Include="../../src/WeatherModel.Data/WeatherModel.Data.csproj" />
    </ItemGroup>

</Project>
