// <auto-generated>
//     Generated by the WeatherSynth.Sample 'exportmodel' command. Do not edit by
//     hand: the numbers below are a fit, and a hand-corrected fit is not a fit.
//
//     To regenerate:
//         dotnet run --project samples/WeatherSynth.Sample -c Release -- exportmodel
//
//     Solar: Bochum 7365, 6,328 days, 2009-01-01 to 2026-06-30
//     Wind:  Essen-Bredeney 1303, 6,207 days, 2009-01-01 to 2025-12-31
//
//     What is NOT in here, deliberately: the clear-sky ceiling, which is recomputed
//     at runtime from the site's geometry and the fitted Linke turbidity table, and
//     both sites, which are already public constants (DwdSolarStations.Bochum,
//     DwdWindStations.EssenBredeney). Only the stochastic half is frozen here.
// </auto-generated>

namespace WeatherSynth.Data;

/// <summary>
/// The bundled model, as coefficients. Rebuilt by <c>SyntheticWeather</c> through each
/// model's <c>FromCoefficients</c>, which skips fitting entirely.
///
/// <para>The twelve monthly entries are already <i>effective</i>: each model's Fit
/// substitutes the pooled fit for months too thin to stand alone, and does so once, at
/// fit time. There is no fallback left to re-apply on load.</para>
/// </summary>
internal static class BochumEssenCoefficients
{
    // Clear-sky index: twelve Beta fits on [0, 1.25].
    // Days per month: 459, 419, 519, 534, 545, 500, 506, 524, 468, 459, 445, 401
    internal const double SolarSupport = 1.25;
    internal const double SolarPersistence = 0.35303134672516645;
    internal const double SolarPooledAlpha = 2.034690651416426;
    internal const double SolarPooledBeta = 2.265621371201927;

    internal static readonly double[] SolarAlpha =
    {
        1.4566878512728771, // Jan
        1.446261310430413, // Feb
        1.701675492371119, // Mar
        2.778167185113586, // Apr
        2.865254554451979, // May
        3.2257273954480725, // Jun
        3.763109083664175, // Jul
        3.324465533442966, // Aug
        2.8307011772262123, // Sep
        2.1535265285341416, // Oct
        1.6812956046763103, // Nov
        1.5479826624651296, // Dec
    };

    internal static readonly double[] SolarBeta =
    {
        2.8429262689937116, // Jan
        2.1125170715784396, // Feb
        1.8018637962397164, // Mar
        2.4607933679615166, // Apr
        2.5817680145005215, // May
        2.8724749112119596, // Jun
        3.274391518228067, // Jul
        2.6304263084660593, // Aug
        2.5702935819828885, // Sep
        2.5842057621304524, // Oct
        2.517214183049526, // Nov
        3.343511855296206, // Dec
    };

    // Wind speed: twelve three-parameter Weibull fits at 15 m.
    // Days per month: 527, 478, 527, 509, 527, 507, 525, 525, 506, 523, 508, 524
    internal const double WindPersistence = 0.44431084960638373;
    internal const double WindReferenceHeightMeters = 15;
    internal const double WindMeanEnergyPatternFactor = 1.305347471783669;
    internal const double WindPooledShape = 1.916283157945326;
    internal const double WindPooledScale = 2.5689078919122195;
    internal const double WindPooledLocation = 0.9499990500000001;

    internal static readonly double[] WindShape =
    {
        1.8383708068326785, // Jan
        1.8730617110947378, // Feb
        1.7648084134954631, // Mar
        1.9865802524048093, // Apr
        1.8357609980814824, // May
        2.000866941265058, // Jun
        1.865982336610816, // Jul
        1.865098024611405, // Aug
        1.6505369912477201, // Sep
        2.218170564561998, // Oct
        1.6087638616957651, // Nov
        2.121505089995794, // Dec
    };

    internal static readonly double[] WindScale =
    {
        3.0345630597697064, // Jan
        3.051101865116142, // Feb
        2.585566212548378, // Mar
        2.2439617367432225, // Apr
        1.7934977547407553, // May
        1.849766376426939, // Jun
        1.7068843252991457, // Jul
        1.7111860564471861, // Aug
        1.8526283287449112, // Sep
        2.919583610833141, // Oct
        2.574305058746978, // Nov
        3.275058053746513, // Dec
    };

    internal static readonly double[] WindLocation =
    {
        0.9499545187945313, // Jan
        1.1041655625, // Feb
        1.1541655125, // Mar
        1.1624988375, // Apr
        1.3875462687023437, // May
        1.2220209133945314, // Jun
        1.2284758548562502, // Jul
        1.2019855167632814, // Aug
        1.1166306542015623, // Sep
        0.673990992675, // Oct
        1.1208322125, // Nov
        0.9271350103640623, // Dec
    };

    // Intra-day shape: least squares of log(EPF) on log(mean speed). The turbine yield
    // and the hourly speeds consume it; daily speed generation is untouched by it.
    internal const double IntradayIntercept = 0.3943817616578898;
    internal const double IntradaySlope = -0.1284512788719823;
    internal const double IntradayPooledEnergyPatternFactor = 1.305347471783669;
    internal const int IntradaySampleCount = 6186;

    // Hourly ordering: the calibrated hourly persistence, and per month the diurnal
    // weight and its standardised pattern by UTC hour. Only the hours consume these;
    // no daily value depends on them.
    internal const double HourlyPersistence = 0.9123154792436652;
    internal const int HourlySampleCount = 6186;

    internal static readonly double[] DiurnalWeight =
    {
        0.18480308988205468, // Jan
        0.29171725376536844, // Feb
        0.44145153393375997, // Mar
        0.504586796369007, // Apr
        0.5041016561153534, // May
        0.4740790108464079, // Jun
        0.5691666797093128, // Jul
        0.5262846731785366, // Aug
        0.49388105499431495, // Sep
        0.3438769997998385, // Oct
        0.2112886003161682, // Nov
        0.10143391995949556, // Dec
    };

    internal static readonly double[] DiurnalPattern =
    {
        -0.021419039701800743, // Jan 00h UTC
        -0.4944723452214851, // Jan 01h UTC
        -0.7891351819647046, // Jan 02h UTC
        -0.8067218700543551, // Jan 03h UTC
        -0.8195106599632893, // Jan 04h UTC
        -0.8978516287122814, // Jan 05h UTC
        -0.7982147334479892, // Jan 06h UTC
        -0.7995000097554038, // Jan 07h UTC
        -0.45079909806545493, // Jan 08h UTC
        -0.17363683500691027, // Jan 09h UTC
        0.408197312483109, // Jan 10h UTC
        1.3188621458355103, // Jan 11h UTC
        2.314351358493169, // Jan 12h UTC
        2.5498316920514177, // Jan 13h UTC
        1.9497740029396888, // Jan 14h UTC
        0.7219161784995093, // Jan 15h UTC
        -0.3930388904116464, // Jan 16h UTC
        -0.6537172935702436, // Jan 17h UTC
        -0.3148853742036065, // Jan 18h UTC
        -0.41774591778607406, // Jan 19h UTC
        -0.18933534038732253, // Jan 20h UTC
        -0.392151636098271, // Jan 21h UTC
        -0.41245023659507074, // Jan 22h UTC
        -0.4383465993564944, // Jan 23h UTC
        -0.6910330069031306, // Feb 00h UTC
        -0.7717276907959828, // Feb 01h UTC
        -0.7282493848835225, // Feb 02h UTC
        -0.8149865503288201, // Feb 03h UTC
        -0.7888137491212632, // Feb 04h UTC
        -0.8979107245901065, // Feb 05h UTC
        -0.7444257801663816, // Feb 06h UTC
        -0.8119562673874833, // Feb 07h UTC
        -0.8508468725884336, // Feb 08h UTC
        -0.19605862859896236, // Feb 09h UTC
        0.763360214262199, // Feb 10h UTC
        1.4133763739398015, // Feb 11h UTC
        1.8132548290969586, // Feb 12h UTC
        2.15246899888719, // Feb 13h UTC
        1.968820856672437, // Feb 14h UTC
        1.3893897816411742, // Feb 15h UTC
        0.772553040787019, // Feb 16h UTC
        -0.1814138168668926, // Feb 17h UTC
        -0.6680322189118494, // Feb 18h UTC
        -0.4327183113347631, // Feb 19h UTC
        -0.30241841300411887, // Feb 20h UTC
        -0.35285756481522007, // Feb 21h UTC
        -0.5087800220292191, // Feb 22h UTC
        -0.5309950929606307, // Feb 23h UTC
        -0.6481707215894165, // Mar 00h UTC
        -0.773508676716416, // Mar 01h UTC
        -0.8330878842711481, // Mar 02h UTC
        -0.8667419654188252, // Mar 03h UTC
        -0.992584511644684, // Mar 04h UTC
        -0.9870300017406963, // Mar 05h UTC
        -0.8733050235390583, // Mar 06h UTC
        -0.7989880973371553, // Mar 07h UTC
        -0.3668593292947718, // Mar 08h UTC
        0.27016269809552024, // Mar 09h UTC
        0.8686252165698701, // Mar 10h UTC
        1.2418667777766992, // Mar 11h UTC
        1.5804666203753108, // Mar 12h UTC
        1.8250179718794064, // Mar 13h UTC
        1.8600540388235274, // Mar 14h UTC
        1.5131276745255358, // Mar 15h UTC
        1.2040482066275857, // Mar 16h UTC
        0.5101406803539152, // Mar 17h UTC
        -0.5352532983243867, // Mar 18h UTC
        -0.8042872602880126, // Mar 19h UTC
        -0.6831737820619064, // Mar 20h UTC
        -0.5068050458486715, // Mar 21h UTC
        -0.5690214251436179, // Mar 22h UTC
        -0.6346928618086035, // Mar 23h UTC
        -0.6512897075156617, // Apr 00h UTC
        -0.8589663605689067, // Apr 01h UTC
        -0.967002760232078, // Apr 02h UTC
        -1.113531656625592, // Apr 03h UTC
        -1.0772736965515648, // Apr 04h UTC
        -1.197878985514212, // Apr 05h UTC
        -1.095561525531004, // Apr 06h UTC
        -0.7309389992631092, // Apr 07h UTC
        -0.056536935161383826, // Apr 08h UTC
        0.47601451484493085, // Apr 09h UTC
        0.9912951790115289, // Apr 10h UTC
        1.4122777466522256, // Apr 11h UTC
        1.596007251264205, // Apr 12h UTC
        1.5905055317624688, // Apr 13h UTC
        1.5086604195268487, // Apr 14h UTC
        1.4022989264069243, // Apr 15h UTC
        1.0260832097155992, // Apr 16h UTC
        0.8192851598075737, // Apr 17h UTC
        0.13219811089808042, // Apr 18h UTC
        -0.6443014896875643, // Apr 19h UTC
        -0.7183772231675191, // Apr 20h UTC
        -0.6098778286553675, // Apr 21h UTC
        -0.5880931873709726, // Apr 22h UTC
        -0.6449956940454508, // Apr 23h UTC
        -0.8414002271289572, // May 00h UTC
        -0.8696612266311124, // May 01h UTC
        -0.8893663837894122, // May 02h UTC
        -1.0998149024945416, // May 03h UTC
        -1.1525242676220009, // May 04h UTC
        -1.2440958010502912, // May 05h UTC
        -0.9101725068290564, // May 06h UTC
        -0.30994824954067784, // May 07h UTC
        0.2081442171735117, // May 08h UTC
        0.5950900792722766, // May 09h UTC
        1.1312623320748867, // May 10h UTC
        1.4370650539897982, // May 11h UTC
        1.4191996844694923, // May 12h UTC
        1.5247850602755824, // May 13h UTC
        1.4286517619603702, // May 14h UTC
        1.2389430208190508, // May 15h UTC
        1.1459212789855826, // May 16h UTC
        0.8377684493396781, // May 17h UTC
        0.17020189745270584, // May 18h UTC
        -0.4629196742071411, // May 19h UTC
        -0.8313691991546204, // May 20h UTC
        -0.8695159245028813, // May 21h UTC
        -0.8230628053963625, // May 22h UTC
        -0.8331816674658812, // May 23h UTC
        -0.7793754454546706, // Jun 00h UTC
        -0.9242769865815968, // Jun 01h UTC
        -1.01612052909778, // Jun 02h UTC
        -1.136028622705137, // Jun 03h UTC
        -1.1077848833224417, // Jun 04h UTC
        -1.1784639906897982, // Jun 05h UTC
        -0.8801555797156424, // Jun 06h UTC
        -0.1298443487768799, // Jun 07h UTC
        0.2677632229214721, // Jun 08h UTC
        0.7511005857447883, // Jun 09h UTC
        1.1123164559316854, // Jun 10h UTC
        1.538564698071999, // Jun 11h UTC
        1.6018832864249666, // Jun 12h UTC
        1.4619522830067602, // Jun 13h UTC
        1.328210773553496, // Jun 14h UTC
        1.2828985203623007, // Jun 15h UTC
        0.8020066500239242, // Jun 16h UTC
        0.6952654064887356, // Jun 17h UTC
        0.23195992723194434, // Jun 18h UTC
        -0.40991924975848043, // Jun 19h UTC
        -0.9156613249201229, // Jun 20h UTC
        -0.981788135117985, // Jun 21h UTC
        -0.8028103942741867, // Jun 22h UTC
        -0.8116923193473503, // Jun 23h UTC
        -1.014148522769848, // Jul 00h UTC
        -1.0655611151181335, // Jul 01h UTC
        -1.0293470982054644, // Jul 02h UTC
        -1.060668778075493, // Jul 03h UTC
        -1.0526421663402576, // Jul 04h UTC
        -0.9881051674160541, // Jul 05h UTC
        -0.8137490169535595, // Jul 06h UTC
        -0.2177475962188838, // Jul 07h UTC
        0.37004351492831994, // Jul 08h UTC
        0.8046318666970532, // Jul 09h UTC
        1.1518632186575897, // Jul 10h UTC
        1.365984606754598, // Jul 11h UTC
        1.4486463858987362, // Jul 12h UTC
        1.536438576781579, // Jul 13h UTC
        1.3947356408922997, // Jul 14h UTC
        1.27043141579866, // Jul 15h UTC
        1.0503918055161823, // Jul 16h UTC
        0.6893859397686406, // Jul 17h UTC
        0.11840572969137327, // Jul 18h UTC
        -0.4964754466271279, // Jul 19h UTC
        -0.8102874130099912, // Jul 20h UTC
        -0.9876992467238206, // Jul 21h UTC
        -0.8842465131156871, // Jul 22h UTC
        -0.7802806208107114, // Jul 23h UTC
        -0.7333362913985678, // Aug 00h UTC
        -0.7459258605775246, // Aug 01h UTC
        -0.7929988883663269, // Aug 02h UTC
        -0.8007323228429049, // Aug 03h UTC
        -0.8436128529806944, // Aug 04h UTC
        -0.9571195040689037, // Aug 05h UTC
        -0.8816576252060926, // Aug 06h UTC
        -0.5126838511681675, // Aug 07h UTC
        0.18802170537776694, // Aug 08h UTC
        0.7314743658391937, // Aug 09h UTC
        1.1613130451238096, // Aug 10h UTC
        1.5312942266752123, // Aug 11h UTC
        1.6550312661577744, // Aug 12h UTC
        1.6550864019287967, // Aug 13h UTC
        1.5316927150358084, // Aug 14h UTC
        1.316603858408038, // Aug 15h UTC
        0.8811122134305017, // Aug 16h UTC
        0.4005863184410703, // Aug 17h UTC
        -0.25589977901222655, // Aug 18h UTC
        -0.8345278603250911, // Aug 19h UTC
        -0.9865149901795086, // Aug 20h UTC
        -0.9942845459047429, // Aug 21h UTC
        -0.9522977420458055, // Aug 22h UTC
        -0.7606240023414161, // Aug 23h UTC
        -0.6169052377994101, // Sep 00h UTC
        -0.6496833768045374, // Sep 01h UTC
        -0.5457411224459664, // Sep 02h UTC
        -0.666023554589363, // Sep 03h UTC
        -0.7725561326930995, // Sep 04h UTC
        -0.7873640945750471, // Sep 05h UTC
        -0.8903572970334912, // Sep 06h UTC
        -0.689162001070497, // Sep 07h UTC
        -0.01717248711019836, // Sep 08h UTC
        0.7336604966159155, // Sep 09h UTC
        1.21538166579812, // Sep 10h UTC
        1.474219496141149, // Sep 11h UTC
        1.7218469024164476, // Sep 12h UTC
        1.7634616421065878, // Sep 13h UTC
        1.635206236555198, // Sep 14h UTC
        1.3654279863490197, // Sep 15h UTC
        0.8232890428868213, // Sep 16h UTC
        0.024234376686629245, // Sep 17h UTC
        -0.8648647236216395, // Sep 18h UTC
        -1.0778270087304964, // Sep 19h UTC
        -0.9693757178098608, // Sep 20h UTC
        -0.8246444861823384, // Sep 21h UTC
        -0.728396140590256, // Sep 22h UTC
        -0.6566544644996876, // Sep 23h UTC
        -0.7843469696752695, // Oct 00h UTC
        -0.8366509483673504, // Oct 01h UTC
        -0.7714748006624844, // Oct 02h UTC
        -0.6778373450337342, // Oct 03h UTC
        -0.6054934624679389, // Oct 04h UTC
        -0.5395968550274998, // Oct 05h UTC
        -0.5294950242717019, // Oct 06h UTC
        -0.5843026011070371, // Oct 07h UTC
        -0.12276544653478955, // Oct 08h UTC
        0.7846226531706441, // Oct 09h UTC
        1.4907979138439669, // Oct 10h UTC
        1.8632288613544181, // Oct 11h UTC
        2.060235898078399, // Oct 12h UTC
        1.863464695776333, // Oct 13h UTC
        1.3912841339943642, // Oct 14h UTC
        0.9185181483926813, // Oct 15h UTC
        -0.07002941950412302, // Oct 16h UTC
        -0.9393477924618807, // Oct 17h UTC
        -0.8902301609685391, // Oct 18h UTC
        -0.7181097051465571, // Oct 19h UTC
        -0.6407215959654474, // Oct 20h UTC
        -0.5598262030017653, // Oct 21h UTC
        -0.5130469491869295, // Oct 22h UTC
        -0.5888770252277594, // Oct 23h UTC
        -0.6518313932524582, // Nov 00h UTC
        -0.6332653923330904, // Nov 01h UTC
        -0.6070512134301478, // Nov 02h UTC
        -0.6700790099482873, // Nov 03h UTC
        -0.7198179263472678, // Nov 04h UTC
        -0.7016676214496727, // Nov 05h UTC
        -0.8374020694031167, // Nov 06h UTC
        -0.8018822777986736, // Nov 07h UTC
        -0.6330654464305044, // Nov 08h UTC
        0.35598877653593386, // Nov 09h UTC
        1.0942886019415852, // Nov 10h UTC
        2.129976670190105, // Nov 11h UTC
        2.149868189950611, // Nov 12h UTC
        2.0513797196168726, // Nov 13h UTC
        1.5228356712347346, // Nov 14h UTC
        0.6583820529958145, // Nov 15h UTC
        -0.7138001929496467, // Nov 16h UTC
        -0.8569663895780799, // Nov 17h UTC
        -0.5657927198022471, // Nov 18h UTC
        -0.09686281174150857, // Nov 19h UTC
        -0.32875839240437954, // Nov 20h UTC
        -0.221086960629102, // Nov 21h UTC
        -0.4417735295772995, // Nov 22h UTC
        -0.4816163353901766, // Nov 23h UTC
        -0.3534389941814343, // Dec 00h UTC
        -0.38736818762223646, // Dec 01h UTC
        -0.004746742773826347, // Dec 02h UTC
        -0.4540307290385125, // Dec 03h UTC
        -0.37420656063976776, // Dec 04h UTC
        -0.4695937055868396, // Dec 05h UTC
        -1.0511823853214812, // Dec 06h UTC
        -0.45007648140702244, // Dec 07h UTC
        -0.6185340007312224, // Dec 08h UTC
        0.02056646587159086, // Dec 09h UTC
        1.0959391923998836, // Dec 10h UTC
        2.3300363836858216, // Dec 11h UTC
        2.2959253761023373, // Dec 12h UTC
        2.1299939412342885, // Dec 13h UTC
        0.7402364057751852, // Dec 14h UTC
        -0.6637777649419344, // Dec 15h UTC
        -1.2084352479817315, // Dec 16h UTC
        -1.3004222758761887, // Dec 17h UTC
        -0.7681676785914064, // Dec 18h UTC
        -0.3145588329336065, // Dec 19h UTC
        -0.42057367916821564, // Dec 20h UTC
        0.12930045959811587, // Dec 21h UTC
        0.0158377028255269, // Dec 22h UTC
        0.08127733930267639, // Dec 23h UTC
    };

    // Solar-wind coupling, solar first. Months below the minimum carry the pooled
    // coefficient; the counts are kept so IsPooled can still say which those were.
    // Pairs per month: 428, 390, 489, 503, 520, 470, 504, 522, 464, 456, 443, 398
    internal const double CouplingPooled = -0.10788256714577305;

    internal static readonly double[] CouplingByMonth =
    {
        -0.16081012286509733, // Jan
        -0.11276706676079853, // Feb
        -0.1265159025071926, // Mar
        -0.005355907367998258, // Apr
        -0.03785403117199978, // May
        -0.0071508886564665905, // Jun
        -0.21979988820617638, // Jul
        -0.187408450586645, // Aug
        -0.1365062677187737, // Sep
        -0.05347097156201545, // Oct
        -0.12471823710481292, // Nov
        -0.13188810182078797, // Dec
    };

    internal static readonly int[] CouplingCounts =
    {
        428, // Jan
        390, // Feb
        489, // Mar
        503, // Apr
        520, // May
        470, // Jun
        504, // Jul
        522, // Aug
        464, // Sep
        456, // Oct
        443, // Nov
        398, // Dec
    };
}
