// <auto-generated>
//     Generated by the WeatherSynth.Sample 'exportmodel' command. Do not edit by
//     hand: the numbers below are a fit, and a hand-corrected fit is not a fit.
//
//     To regenerate:
//         dotnet run --project samples/WeatherSynth.Sample -c Release -- exportmodel
//
//     Solar: Bochum 7365, 6,328 days, 2009-01-01 to 2026-06-30
//     Wind:  Essen-Bredeney 1303, 6,207 days, 2009-01-01 to 2025-12-31
//
//     What is NOT in here, deliberately: the clear-sky ceiling, which is recomputed
//     at runtime from the site's geometry and the fitted Linke turbidity table, and
//     both sites, which are already public constants (DwdStations.Bochum,
//     DwdWindStations.EssenBredeney). Only the stochastic half is frozen here.
// </auto-generated>

namespace WeatherSynth.Data;

/// <summary>
/// The bundled model, as coefficients. Rebuilt by <c>SyntheticWeather</c> through each
/// model's <c>FromCoefficients</c>, which skips fitting entirely.
///
/// <para>The twelve monthly entries are already <i>effective</i>: each model's Fit
/// substitutes the pooled fit for months too thin to stand alone, and does so once, at
/// fit time. There is no fallback left to re-apply on load.</para>
/// </summary>
internal static class BochumEssenCoefficients
{
    // Clear-sky index: twelve Beta fits on [0, 1.25].
    // Days per month: 459, 419, 519, 534, 545, 500, 506, 524, 468, 459, 445, 401
    internal const double SolarSupport = 1.25;
    internal const double SolarPersistence = 0.35303134672516645;
    internal const double SolarPooledAlpha = 2.034690651416426;
    internal const double SolarPooledBeta = 2.265621371201927;

    internal static readonly double[] SolarAlpha =
    {
        1.4566878512728771, // Jan
        1.446261310430413, // Feb
        1.701675492371119, // Mar
        2.778167185113586, // Apr
        2.865254554451979, // May
        3.2257273954480725, // Jun
        3.763109083664175, // Jul
        3.324465533442966, // Aug
        2.8307011772262123, // Sep
        2.1535265285341416, // Oct
        1.6812956046763103, // Nov
        1.5479826624651296, // Dec
    };

    internal static readonly double[] SolarBeta =
    {
        2.8429262689937116, // Jan
        2.1125170715784396, // Feb
        1.8018637962397164, // Mar
        2.4607933679615166, // Apr
        2.5817680145005215, // May
        2.8724749112119596, // Jun
        3.274391518228067, // Jul
        2.6304263084660593, // Aug
        2.5702935819828885, // Sep
        2.5842057621304524, // Oct
        2.517214183049526, // Nov
        3.343511855296206, // Dec
    };

    // Wind speed: twelve three-parameter Weibull fits at 15 m.
    // Days per month: 527, 478, 527, 509, 527, 507, 525, 525, 506, 523, 508, 524
    internal const double WindPersistence = 0.44431084960638373;
    internal const double WindReferenceHeightMeters = 15;
    internal const double WindMeanEnergyPatternFactor = 1.305347471783669;
    internal const double WindPooledShape = 1.916283157945326;
    internal const double WindPooledScale = 2.5689078919122195;
    internal const double WindPooledLocation = 0.9499990500000001;

    internal static readonly double[] WindShape =
    {
        1.8383708068326785, // Jan
        1.8730617110947378, // Feb
        1.7648084134954631, // Mar
        1.9865802524048093, // Apr
        1.8357609980814824, // May
        2.000866941265058, // Jun
        1.865982336610816, // Jul
        1.865098024611405, // Aug
        1.6505369912477201, // Sep
        2.218170564561998, // Oct
        1.6087638616957651, // Nov
        2.121505089995794, // Dec
    };

    internal static readonly double[] WindScale =
    {
        3.0345630597697064, // Jan
        3.051101865116142, // Feb
        2.585566212548378, // Mar
        2.2439617367432225, // Apr
        1.7934977547407553, // May
        1.849766376426939, // Jun
        1.7068843252991457, // Jul
        1.7111860564471861, // Aug
        1.8526283287449112, // Sep
        2.919583610833141, // Oct
        2.574305058746978, // Nov
        3.275058053746513, // Dec
    };

    internal static readonly double[] WindLocation =
    {
        0.9499545187945313, // Jan
        1.1041655625, // Feb
        1.1541655125, // Mar
        1.1624988375, // Apr
        1.3875462687023437, // May
        1.2220209133945314, // Jun
        1.2284758548562502, // Jul
        1.2019855167632814, // Aug
        1.1166306542015623, // Sep
        0.673990992675, // Oct
        1.1208322125, // Nov
        0.9271350103640623, // Dec
    };

    // Intra-day shape: least squares of log(EPF) on log(mean speed). Only the turbine
    // yield consumes it; speed generation is untouched by it.
    internal const double IntradayIntercept = 0.3943817616578898;
    internal const double IntradaySlope = -0.1284512788719823;
    internal const double IntradayPooledEnergyPatternFactor = 1.305347471783669;
    internal const int IntradaySampleCount = 6186;

    // Solar-wind coupling, solar first. Months below the minimum carry the pooled
    // coefficient; the counts are kept so IsPooled can still say which those were.
    // Pairs per month: 428, 390, 489, 503, 520, 470, 504, 522, 464, 456, 443, 398
    internal const double CouplingPooled = -0.10788256714577305;

    internal static readonly double[] CouplingByMonth =
    {
        -0.16081012286509733, // Jan
        -0.11276706676079853, // Feb
        -0.1265159025071926, // Mar
        -0.005355907367998258, // Apr
        -0.03785403117199978, // May
        -0.0071508886564665905, // Jun
        -0.21979988820617638, // Jul
        -0.187408450586645, // Aug
        -0.1365062677187737, // Sep
        -0.05347097156201545, // Oct
        -0.12471823710481292, // Nov
        -0.13188810182078797, // Dec
    };

    internal static readonly int[] CouplingCounts =
    {
        428, // Jan
        390, // Feb
        489, // Mar
        503, // Apr
        520, // May
        470, // Jun
        504, // Jul
        522, // Aug
        464, // Sep
        456, // Oct
        443, // Nov
        398, // Dec
    };
}
